; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
monitor_speed = 115200
lib_deps = 
	jgromes/RadioLib@^6.6.0
	stevemarple/MicroNMEA@^2.0.6
	asukiaaa/MPU9250_asukiaaa@^1.5.12
	jakalada/ADXL345@^0.2.0
	esphome/AsyncTCP-esphome@^1.2.2
	esphome/ESPAsyncWebServer-esphome@^2.1.0
	bblanchon/ArduinoJson@^7.1.0
	lewisxhe/XPowersLib@^0.2.6
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/Adafruit GFX Library@^1.11.11
	adafruit/Adafruit SSD1306@^2.5.13
	adafruit/Adafruit SH110X@^2.1.11
	mathertel/OneButton@^2.6.1

[env:ttgo-lora32-sx1278]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DLORA32_SX1278 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t-beam-sx1278]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT_BEAM_SX1278 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t-beam-sx1276]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT_BEAM_SX1276 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t-beam-sx1262]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT_BEAM_SX1262 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v1_3-sx1278]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V1_3_SX1278 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v1_3-sx1276]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V1_3_SX1276 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v1_6-sx1278]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V1_6_SX1278 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v1_6-sx1276-tcxo]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V1_6_SX1276_TCXO -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v3_0-sx1262]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V3_0_SX1262 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v3_0-sx1276]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V3_0_SX1276 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v3_0-sx1278]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V3_0_SX1278 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-v3_0-lr1121]
platform = espressif32
board = esp32dev
board_build.partitions = partitions.csv
build_flags = -DT3_V3_0_LR1121 -DTARGET_ESP32 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""

[env:ttgo-t3-s3-v1_2-sx1262]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv
build_flags = -DT3_S3_V1_2_SX1262 -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
	-DARDUINO_USB_MODE=1	-DARDUINO_USB_CDC_ON_BOOT=1

[env:ttgo-t3-s3-v1_2-sx1276]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv
build_flags = -DT3_S3_V1_2_SX1276 -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
	-DARDUINO_USB_MODE=1	-DARDUINO_USB_CDC_ON_BOOT=1

[env:ttgo-t3-s3-v1_2-sx1278]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv
build_flags = -DT3_S3_V1_2_SX1278 -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
	-DARDUINO_USB_MODE=1	-DARDUINO_USB_CDC_ON_BOOT=1

[env:ttgo-t3-s3-v1_2-lr1121]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv
build_flags = -DT3_S3_V1_2_LR1121 -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
	-DARDUINO_USB_MODE=1	-DARDUINO_USB_CDC_ON_BOOT=1

[env:heltec-tracker]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions.csv
build_flags = -DHELTEC_TRACKER -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
	-DARDUINO_USB_MODE=1	-DARDUINO_USB_CDC_ON_BOOT=1

[env:heltec-lora32]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = partitions_8MB.csv
build_flags = -DHELTEC_LORA32 -DTARGET_ESP32S3 -DCI_BUILD -DVERSION_TAG="\"${sysenv.VERSION_TAG}\""
